-- This file has been generated by Dungeon Editor 2.2.4

-- import standard assets
import "assets/scripts/standard_assets.lua"

-- import custom assets
import "mod_assets/scripts/items.lua"
import "mod_assets/scripts/monsters.lua"
import "mod_assets/scripts/objects.lua"
import "mod_assets/scripts/tiles.lua"
import "mod_assets/scripts/recipes.lua"
import "mod_assets/scripts/spells.lua"
import "mod_assets/scripts/materials.lua"
import "mod_assets/scripts/sounds.lua"

import "assets/scripts/objects/base.lua"
import "assets/scripts/objects/generic.lua"
import "assets/scripts/spells/blob.lua"
import "assets/scripts/monsters/skeleton_knight_trooper.lua"
import "assets/scripts/monsters/uggardian.lua"

G1_TILESETS_USED = {
}

-- Obviously, you need to import this AFTER setting all the variables above.
import "mod_assets/g1/g1.lua"

g1_createWeaponMonster("skeleton_trooper","torch","round_shield","skeleton_torcher")
g1_createWeaponMonster("skeleton_trooper","warhammer","skeleton_knight_shield","skeleton_hammer")