-- This file has been generated by Dungeon Editor 2.2.4

-- TODO: place your custom item definitions here

defineObject{
	name = "green_key",
	baseObject = "base_item",
	components = {
		{
			class = "Model",
			model = "assets/models/items/key_iron.fbx",
		},
		{
			class = "Item",
			uiName = "Key of the Keep",
			gfxIndex = 22,
			weight = 0.2,
			traits = { "key" },
		},
		{
			class = "Particle",
			particleSystem = "glitter_silver",
		},
	},
}

defineObject{
	name = "orb_of_light",
	baseObject = "base_item",
	components = {
		{
			class = "Model",
			model = "assets/models/items/essence_fire.fbx",
		},
		{
			class = "Item",
			uiName = "Orb of the Light",
			gfxIndex = 346,
			impactSound = "impact_blunt",
			weight = 0,
			traits = { "essence" },
		},
		{
			class = "Particle",
			particleSystem = "essence_fire",
		},
		{
			class = "Light",
			offset = vec(0, 0.5, 0),
			range = 1.5,
			color = vec(1, 0.5, 0.25),
			brightness = 30,
			castShadow = false,
		},
	},
}
defineObject{
	name = "orb_of_darkness",
	baseObject = "base_item",
	components = {
		{
			class = "Model",
			model = "assets/models/items/essence_balance.fbx",
		},
		{
			class = "Item",
			uiName = "Orb of Darkness",
			gfxIndex = 345,
			impactSound = "impact_blunt",
			weight = 0,
			traits = { "essence" },
		},
		{
			class = "Light",
			offset = vec(0, 0.3, 0),
			range = 1.5,
			color = vec(0.75, 0.2, 1),
			brightness = 30,
			castShadow = false,
		},
		{
			class = "Particle",
			particleSystem = "essence_balance",
		},
	},
}