-- This file has been generated by Dungeon Editor 2.2.4

-- TODO: place your custom dungeon object definitions here

defineObject{
    name = "boss_light",
    baseObject = "mine_ceiling_pit_light",
	components = {
		{
            class = "Light",
            enabled = true,
			range = 100,
			color = vec(1,0,0),
			brightness = 25,
			castShadow = true,
		},
	},
}

defineObject{
    name = "yellow_light",
    baseObject = "mine_ceiling_pit_light",
	components = {
		{
            class = "Light",
            enabled = true,
			range = 20,
			color = vec(1,.8,.18),
			brightness = 25,
			castShadow = true,
		},
	},
}

defineObject{
    name = "purple_light",
    baseObject = "mine_ceiling_pit_light",
	components = {
		{
            class = "Light",
            enabled = true,
			range = 20,
			color = vec(.58,0,.28),
			brightness = 25,
			castShadow = true,
		},
	},
}

defineObject{
	name = "barrel_crate_container",
	baseObject = "base_obstacle",
	components = {
		{
			class = "Model",
			model = "assets/models/env/barrel_crate_block.fbx",
		},
		{
			class = "Obstacle",
			hitSound = "barrel_hit",
			hitEffect = "hit_wood",
		},
		{
			class = "Clickable",
			offset = vec(0,0.5,0),
			size = vec(1.5, 1.0, 1.0),
			maxDistance = 1,
			--debugDraw = true,
		},
		{
			class = "Surface",
			offset = vec(-0.2,0.5,0.2),
			size = vec(1.5, 0.85),
			--debugDraw = true,
		},	
		placement = "floor"
	},
	editorIcon = 260,
}

defineObject{
	name = "castle_wall_bookshelf_cont",
	baseObject = "base_wall",
	components = {
		{
			class = "Model",
			model = "assets/models/env/castle_wall_bookself_01.fbx",
			staticShadow = true,
		},
		{
			class = "Occluder",
			model = "assets/models/env/castle_wall_01_occluder.fbx",
		},
		{
			class = "Surface",
			offset = vec(-0.7,1.7,0.2),
			size = vec(1.5, 0.85),
			--debugDraw = true,
		},	
	},
	minimalSaveState = true,
	replacesWall = true,
}